<!DOCTYPE html>

<html lang="">

<head>
<title>content/joe/index.page/asyA</title>

<meta http-equiv="content-type" content="text/html; charset=utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<style>
svg, #container {
display: block;
width: 100vw;
height: 100vh;
}
body {margin: 0;}
</style>
</head>

<body>

<!-- This file was generated by dvisvgm 3.0.3 -->
<svg version='1.1' xmlns='http://www.w3.org/2000/svg' xmlns:xlink='http://www.w3.org/1999/xlink' width='708.661418pt' height='708.661418pt' viewBox='410.740157 408.188976 708.661418 708.661418'>
<defs>
<clipPath id='Clip1'>
<path clip-rule='evenodd' d='M-.501875 711.821H711.821V-.501875H-.501875V711.821ZM400.086 177.955C400.086 153.419 380.195 133.529 355.659 133.529C331.124 133.529 311.233 153.419 311.233 177.955S331.124 222.381 355.659 222.381C380.195 222.381 400.086 202.491 400.086 177.955Z' transform='matrix(0.996264 0 0 0.996264 410.74 408.189)'/>
</clipPath>
</defs>
<g id='page1'>
<g transform='translate(410.74 408.189)scale(.996264)'>
<path d='M0 711.319H711.319V0H0V711.319Z' fill='#ffffff'/>
</g>
<g clip-path='url(#Clip1)'>
<g transform='translate(410.74 408.189)scale(.996264)'>
<path d='M355.659 .250937C159.373 .250938 .250938 159.373 .250937 355.659C.250937 551.946 159.373 711.068 355.659 711.068' fill='none' stroke='#000000' stroke-linecap='round' stroke-linejoin='round' stroke-miterlimit='10.0375' stroke-width='0.501875'/>
</g>
<g transform='translate(410.74 408.189)scale(.996264)'>
<path d='M355.659 .250937C165.526 .250937 96.5692 226.114 355.659 355.659C614.75 485.205 545.793 711.068 355.659 711.068C551.946 711.068 711.068 551.946 711.068 355.659C711.068 159.373 551.946 .250937 355.659 .250937Z' fill='#000000'/>
</g>
<g transform='translate(410.74 408.189)scale(.996264)'>
<path d='M355.659 .250937C165.526 .250937 96.5692 226.114 355.659 355.659C614.75 485.205 545.793 711.068 355.659 711.068C551.946 711.068 711.068 551.946 711.068 355.659C711.068 159.373 551.946 .250937 355.659 .250937Z' fill='none' stroke='#000000' stroke-linecap='round' stroke-linejoin='round' stroke-miterlimit='10.0375' stroke-width='0.501875'/>
</g>
</g>
<g transform='translate(410.74 408.189)scale(.996264)'>
<path d='M400.086 533.364C400.086 508.828 380.195 488.938 355.659 488.938C331.124 488.938 311.233 508.828 311.233 533.364S331.124 577.79 355.659 577.79C380.195 577.79 400.086 557.9 400.086 533.364Z' fill='#000000'/>
</g>
</g>
</svg>

</body>

</html>
